import 'package:flutter/widgets.dart';

class AppStrings {
  AppStrings(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('en'), Locale('hi'), Locale('mr')];

  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'email': 'Email',
      'password': 'Password',
      'signIn': 'Sign in',
      'signUp': 'Create account',
      'googleSignIn': 'Continue with Google',
      'displayName': 'Display name',
      'phone': 'Phone',
      'save': 'Save',
      'account': 'Account',
      'appearance': 'Appearance',
      'language': 'Language',
      'notifications': 'Notifications',
      'emergencyAlerts': 'Emergency alerts',
      'light': 'Light',
      'dark': 'Dark',
      'system': 'System',
      'offlineDemo': 'Demo mode',
      'firebaseLive': 'Live mode',
      'signOut': 'Sign out',
      'settingsSaved': 'Settings saved',
      'profileSaved': 'Profile updated',
      'organization': 'Organization',
      'fieldNeeds': 'Field needs',
      'dispatch': 'Dispatch',
      'tasks': 'Tasks',
      'inbox': 'Inbox',
      'active': 'Active',
      'profile': 'Profile',
      'capture': 'Capture',
      'queue': 'Queue',
      'dashboard': 'Dashboard',
      'volunteers': 'Volunteers',
      'map': 'Map',
    },
    'hi': {
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'signIn': 'साइन इन',
      'signUp': 'खाता बनाएं',
      'googleSignIn': 'Google से जारी रखें',
      'displayName': 'डिस्प्ले नाम',
      'phone': 'फ़ोन',
      'save': 'सहेजें',
      'account': 'खाता',
      'appearance': 'रूप',
      'language': 'भाषा',
      'notifications': 'सूचनाएं',
      'emergencyAlerts': 'आपात अलर्ट',
      'light': 'लाइट',
      'dark': 'डार्क',
      'system': 'सिस्टम',
      'offlineDemo': 'डेमो मोड',
      'firebaseLive': 'लाइव मोड',
      'signOut': 'साइन आउट',
      'settingsSaved': 'सेटिंग्स सहेजी गईं',
      'profileSaved': 'प्रोफ़ाइल अपडेट हुई',
      'organization': 'संगठन',
      'fieldNeeds': 'मैदानी आवश्यकताएँ',
      'dispatch': 'डिस्पैच',
      'tasks': 'कार्य',
      'inbox': 'इनबॉक्स',
      'active': 'सक्रिय',
      'profile': 'प्रोफ़ाइल',
      'capture': 'कैप्चर',
      'queue': 'क्यू',
      'dashboard': 'डैशबोर्ड',
      'volunteers': 'स्वयंसेवक',
      'map': 'मैप',
    },
    'mr': {
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'signIn': 'साइन इन',
      'signUp': 'खाते तयार करा',
      'googleSignIn': 'Google सह पुढे जा',
      'displayName': 'दिसणारे नाव',
      'phone': 'फोन',
      'save': 'जतन करा',
      'account': 'खाते',
      'appearance': 'रूप',
      'language': 'भाषा',
      'notifications': 'सूचना',
      'emergencyAlerts': 'तत्काळ अलर्ट',
      'light': 'लाइट',
      'dark': 'डार्क',
      'system': 'सिस्टम',
      'offlineDemo': 'डेमो मोड',
      'firebaseLive': 'लाइव्ह मोड',
      'signOut': 'साइन आउट',
      'settingsSaved': 'सेटिंग्ज जतन झाल्या',
      'profileSaved': 'प्रोफाइल अपडेट झाले',
      'organization': 'संस्था',
      'fieldNeeds': 'मैदानी गरजा',
      'dispatch': 'डिस्पॅच',
      'tasks': 'कामे',
      'inbox': 'इनबॉक्स',
      'active': 'सक्रिय',
      'profile': 'प्रोफाइल',
      'capture': 'नोंद',
      'queue': 'रांग',
      'dashboard': 'डॅशबोर्ड',
      'volunteers': 'स्वयंसेवक',
      'map': 'नकाशा',
    },
  };

  String text(String key) {
    final languageCode = _strings.containsKey(locale.languageCode)
        ? locale.languageCode
        : 'en';
    return _strings[languageCode]?[key] ?? _strings['en']![key] ?? key;
  }
}
